[tool.black]
line-length = 100
target-version = ["py310"]

[tool.ruff]
line-length = 100
select = [
  "E",  # pycodestyle errors
  "F",  # pyflakes
  "I",  # isort
  "B",  # flake8-bugbear
]
ignore = [
  "E501",  # handled by black
  "B008",  # Depends(...) em defaults é padrão do FastAPI
  "B904",  # raise HTTPException from ... (aceitar sem chaining)
]
# Excluir diretórios gerados
exclude = [
  ".venv",
  "__pycache__",
  "build",
  "dist",
]

[tool.ruff.lint.isort]
known-first-party = ["src"]
combine-as-imports = true
